### ISSUE TITLE
java.io.NotSerializableException: org.jpmml.evaluator.ModelEvaluatorFactory

### ISSUE THREAD

**Issue by Make42** [jpmml/jpmml-storm#1]
Hi, I try to get the example to run, but I get the followinig error.

```
  $ storm jar target/example-1.0-SNAPSHOT.jar org.jpmml.storm.Main "/home/user/sample.rf.xml" "/home/user/orders.csv" "/home/user/orders_res.csv"
  ...
  Exception in thread "main" java.lang.RuntimeException: java.io.NotSerializableException: org.jpmml.evaluator.ModelEvaluatorFactory
    at backtype.storm.utils.Utils.serialize(Utils.java:81)
    at backtype.storm.topology.TopologyBuilder.createTopology(TopologyBuilder.java:106)
    at org.jpmml.storm.Main.main(Main.java:95)
  Caused by: java.io.NotSerializableException: org.jpmml.evaluator.ModelEvaluatorFactory
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
    at backtype.storm.utils.Utils.serialize(Utils.java:77)
    ... 2 more
```

I tried to find out, what it is that might not be serializable, but I were not able to find any issue. Could you please tell be what is wrong?

Perhaps you can also provide a test model and test input with which you were able to get this running. That might help in issue discussion. Thank you very much.

**Comment by vruusmann** [comment]
You can use sample models and input files from our [R/Rattle functional testing module](https://github.com/jpmml/jpmml-evaluator/tree/master/pmml-rattle/src/test/resources). For example, use `pmml/DecisionTreeIris.pmml` as a model and `csv/Iris.csv` as an input file:

```
cd pmml-storm-example
storm jar target/example-1.0-SNAPSHOT.jar org.jpmml.storm.Main DecisionTreeIris.pmml Iris.csv output.csv
```

The example application `org.jpmml.storm.Main` should be run in "local" mode. You are getting this `java.io.NotSerializableException`, because you are running it in "cluster" mode.

The example application is not intended for production use. It simply aims to demonstrate how to incorporate the `org.jpmml.storm.PMMLBolt` bolt into your topology.

**Comment by vruusmann** [comment]
I can associate your exception stack trace with a potential bug in the main JPMML-Evaluator library itself. 

Obviously, you are working with a Random Forest (RF) model (ie. the name of the PMML file is `rf.xml`). The evaluation of RF models is handled by a `org.jpmml.evaluator.MiningModelEvaluator` instance, which keeps a reference to the `org.jpmml.evaluator.ModelEvaluatorFactory` that created it. Currently, the serialization fails because the latter class is not marked as serializable.

I will fix it immediately in the JPMML-Evaluator library.

**Comment by Make42** [comment]
Ok, the following seem to have worked:

```
  $ storm jar jpmml-storm/pmml-storm-example/target/example-1.0-SNAPSHOT.jar org.jpmml.storm.Main jpmml-evaluator/pmml-rattle/src/test/resources/pmml/DecisionTreeIris.pmml jpmml-evaluator/pmml-rattle/src/test/resources/csv/Iris.csv output.csv
```

I did not change the code. Where have I switched to cluster mode? I thought I ran "local"ly.

Have you fixed it? What should I do to incorporate the fix into my system? Just run

```
  mvn clear install
```

again?

By the way:

```
  $ storm version
  0.9.4
```

**Comment by vruusmann** [comment]
Please disregard my earlier comment about "local" and "cluster" modes. The example application is definitely hard-coded to run everything locally.

Currently, the situation is that you are able to evaluate all model types except the Random Forest (RF) model type. The evaluator class that handles the RF model type contains an unserializable field. It will throw a `java.io.NotSerializableException` until it's fixed.

The fix will be committed to JPMML-Evaluator library codebase later today. The fixed version will be released to Maven Central repository around the end of this week. If you need it sooner, then you need to build the fixed JPMML-Evaluator JAR file locally and attach it to your JPMML-Storm project.

Stay tuned. I will keep this issue updated as it all happens.

**Comment by Make42** [comment]
Thank you very much! Do you have an out-of-the-box R example (including an R script an an input file) which produces input.csv and model.pmml for me to give to the storm-example? This does not have to be a decision tree - can be something else, but I it can not wait unfortunately.

In https://github.com/jpmml/r2pmml your example is a random forest unfortunately...

**Comment by vruusmann** [comment]
You can find my R sample scripts in the [`R` directory](https://github.com/jpmml/jpmml-evaluator/tree/master/pmml-rattle/src/test/R). They are organized into files based on function type. For example, all classification-type examples are located inside the `ClassificationTest.R` file, and so on.

This `DecisionTreeIris.pmml` file is generated by the `generateDecisionTreeIris()` function:

```
library("rpart")
library("pmml")

irisData = read.csv(file = "csv/Iris.csv", header = TRUE)
irisFormula = formula(Species ~ .)
rpart = rpart(irisFormula, irisData)
saveXML(pmml(rpart), "pmml/DecisionTreeIris.pmml")
```

**Comment by Make42** [comment]
You have a couple of bugs in the file:
readCsv and writeCsv instead of read.csv and write.csv

**Comment by vruusmann** [comment]
I have implemented the fix. Here is what you need to do if you want to start evaluating Random Forest (RF) models already today:

First, check out and build the latest version of the JPMML-Evaluator project. This will install the fixed JAR file `org.jpmml:pmml-evaluator:1.1-SNAPSHOT.jar` into your local Maven repository.

Then, check out the latest version of the JPMML-Storm project. Open the `pmml-storm/pom.xml` file in your favourite text editor and on line 18 change the version of the JPMML-Evaluator dependency from `1.1.19` to `1.1-SNAPSHOT`. Save changes and rebuild the project using `mvn clean install`. The newly built test application can evaluate RF models without problem - go ahead and test it with the `RandomForestIris.pmml` file.

I will keep this issue open until the JPMML-Evaluator library version 1.1.20 has been released and integrated into the JPMML-Storm project.

**Comment by Make42** [comment]
Thank you very much, and kudos for the fast response!
I am looking forward to the advances of this exiting project.
